# Generated by Django 3.1.7 on 2021-03-08 13:38

import datetime_utils.date_time
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff_groups', '0001_initial'),
        ('wallet_models', '0003_walletwithdraw'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('cost_build_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('ordered_date', models.DateField(default=datetime_utils.date_time.DateTime.datenow)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('finished_date', models.DateField(blank=True, null=True)),
                ('build_status', models.CharField(blank=True, choices=[('INITIATED', 'initiated'), ('PROGRESS', 'progress'), ('COMPLETED', 'completed'), ('FAILED', 'failed'), ('CLOSED', 'closed')], max_length=255, null=True)),
                ('is_transferred', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet_models.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBuildWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_build_worker', to='product_builds.productbuild')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_groups.staffworker')),
            ],
        ),
    ]
