# Generated by Django 3.1.7 on 2021-03-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_builds', '0002_productbuild_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbuild',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
    ]
