# Generated by Django 3.1.7 on 2021-03-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_models', '0003_walletwithdraw'),
        ('product_stocks', '0002_productstock_product'),
        ('product_builds', '0003_productbuild_is_paid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductBuild',
            new_name='ProductBuildStock',
        ),
    ]
