# Generated by Django 3.1.7 on 2021-03-11 14:54

import datetime_utils.date_time
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_builds', '0004_auto_20210311_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('ordered_date', models.DateField(default=datetime_utils.date_time.DateTime.datenow)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('finished_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Product builds',
                'verbose_name_plural': 'Product builds',
            },
        ),
        migrations.AddField(
            model_name='productbuildstock',
            name='build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_build', to='product_builds.productbuild'),
        ),
    ]
