# Generated by Django 3.1.7 on 2021-03-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_builds', '0005_auto_20210311_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbuildstock',
            name='finished_date',
        ),
        migrations.RemoveField(
            model_name='productbuildstock',
            name='ordered_date',
        ),
        migrations.RemoveField(
            model_name='productbuildstock',
            name='required_date',
        ),
    ]
