# Generated by Django 3.1.7 on 2021-04-09 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_builds', '0007_auto_20210315_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbuild',
            options={'ordering': ['-required_date'], 'verbose_name': 'Product builds', 'verbose_name_plural': 'Product builds'},
        ),
    ]
