# Generated by Django 3.1.7 on 2021-04-09 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_builds', '0008_auto_20210409_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbuild',
            options={'verbose_name': 'Product builds', 'verbose_name_plural': 'Product builds'},
        ),
    ]
