# Generated by Django 3.1.7 on 2021-03-08 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('product_stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_stock', to='products.product'),
        ),
    ]
