# Generated by Django 3.1.7 on 2021-03-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_supplies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsupplystock',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
    ]
